version: '3.8'

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:

services:
  mongodb:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - mongodb_data:/data/db

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"  # Connect to the Zookeeper service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
    depends_on:
      - zookeeper  # Ensure Zookeeper starts before Kafka

  app:
    build:
      context: .
    container_name: express-app-container
    depends_on:
      - mongodb
      - kafka
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongo-container:27017"
      KAFKA_BROKER: "kafka-container:9092"
